name: web_dynamic
on:
  push:
    branches:
      - 'main'
      - 'master'
  schedule:
    - cron: '0 0 * * *'

permissions: read-all

jobs:
  builds:
    name: run-app
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16

      - run: make help
      - run: make build-docker
      - run: make node-start