name: web_dynamic
on:
  push:
    branches:
      - 'main'
      - 'master'
  schedule:
    - cron: '0 0 * * *'

permissions: read-all

jobs:
  builds:
    name: run-app
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: make build-docker
      - uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD}}
      - run: make help
